### ISSUE TITLE
Implement CI/CD in the repository

### ISSUE THREAD

**Issue by JankowskiDaniel** [JankowskiDaniel/Neural-Deep-Retina#10]
CI/CD:
- lint
- type checking
- tests (optionally)

**Comment by kapiblue** [comment]
Added a flake8 config and fixed the flake errors in commit 7cf810b4a3e735e751fd17c54b87089a3e6298b6

**Comment by kapiblue** [comment]
Fixed initial mypy errors in commit 809138618cf189ed8accdb2a11bda679176f2397

**Comment by kapiblue** [comment]
Successfully set up with flake8, mypy, and checking for tests (by default in `tests` directory).
